/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: UROD Engine (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import computerScene from '../assets/3d/computer.glb'
import { a } from '@react-spring/three'

const Computer = (props) => {
  const computerRef = useRef();

  const { nodes, materials } = useGLTF(computerScene);
  
  return (
    <a.group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Cube_PC_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cube_LightMat_0.geometry}
              material={materials.LightMat}
            />
            <mesh
              geometry={nodes.Cube_Screen_0.geometry}
              material={materials.Screen}
            />
            <mesh
              geometry={nodes.Cube_Keyboard_0.geometry}
              material={materials.Keyboard}
            />
          </group>
        </group>
      </group>
    </a.group>
  )
}

export default Computer;